=== nali001/research_asset_search/preprocessor/notebook/schemas/kaggle_metadata_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Kaggle metadata schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the kernel"
    },
    "id_no": {
      "type": "integer",
      "description": "Numeric identifier for the kernel"
    },
    "title": {
      "type": "string",
      "description": "Title or name of the kernel"
    },
    "code_file": {
      "type": "string",
      "description": "Filename of the kernel code file"
    },
    "language": {
      "type": "string",
      "description": "Language in which the kernel is written"
    },
    "kernel_type": {
      "type": "string",
      "description": "Type of kernel"
    },
    "is_private": {
      "type": "boolean",
      "description": "Whether the kernel is private or public"
    },
    "enable_gpu": {
      "type": "boolean",
      "description": "Whether the kernel is enabled for GPU processing"
    },
    "enable_internet": {
      "type": "boolean",
      "description": "Whether the kernel has access to the internet"
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Keywords associated with the kernel"
    },
    "dataset_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any datasets used in the kernel"
    },
    "kernel_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any other kernels used in the kernel"
    },
    "competition_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any competitions used in the kernel"
    }
  },
  "required": [
    "id",
    "id_no",
    "title",
    "code_file",
    "language",
    "kernel_type",
    "is_private",
    "enable_gpu",
    "enable_internet",
    "keywords",
    "dataset_sources",
    "kernel_sources",
    "competition_sources"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/habibmrad1983_prostate-cancer-in-depth-understanding-eda-model.json
{
  "id": "habibmrad1983/prostate-cancer-in-depth-understanding-eda-model",
  "id_no": 15569815,
  "title": "Prostate Cancer: In Depth Understanding,EDA ,Model",
  "code_file": "prostate-cancer-in-depth-understanding-eda-model.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/prostate-cancer-grade-assessment"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/fx6300_clam-strip-ai-image-generation.json
{
  "id": "fx6300/clam-strip-ai-image-generation",
  "id_no": 30713367,
  "title": "\ud83d\udc1aCLAM STRIP AI [image generation]\ud83d\udc1a",
  "code_file": "clam-strip-ai-image-generation.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [
    "code/analokamus/how-to-use-pyvips-offline"
  ],
  "competition_sources": [
    "competitions/mayo-clinic-strip-ai"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/foobar167_panda-dataset-getting-started.json
{
  "id": "foobar167/panda-dataset-getting-started",
  "id_no": 9301002,
  "title": "PANDA dataset - getting started",
  "code_file": "panda-dataset-getting-started.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/prostate-cancer-grade-assessment"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/vbookshelf_part-1-breast-cancer-analyzer-web-app.json
{
  "id": "vbookshelf/part-1-breast-cancer-analyzer-web-app",
  "id_no": 2270637,
  "title": "Part 1 : Breast Cancer Analyzer + Web App",
  "code_file": "part-1-breast-cancer-analyzer-web-app.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": true,
  "enable_internet": true,
  "keywords": [
    "cancer"
  ],
  "dataset_sources": [
    "datasets/paultimothymooney/breast-histopathology-images"
  ],
  "kernel_sources": [],
  "competition_sources": []
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/kerneler_starter-camelyon16-cancer-wsi-list-fb14cfc6-7.json
{
  "id": "kerneler/starter-camelyon16-cancer-wsi-list-fb14cfc6-7",
  "id_no": 3671642,
  "title": "Starter: Camelyon16 Cancer WSI List fb14cfc6-7",
  "code_file": "starter-camelyon16-cancer-wsi-list-fb14cfc6-7.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    "datasets/kokecacao/camelyon16-cancer-wsi-list-normal-050"
  ],
  "kernel_sources": [],
  "competition_sources": []
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/kerneler_starter-mitosis-wsi-ccmct-training-set-48450e6f-5.json
{
  "id": "kerneler/starter-mitosis-wsi-ccmct-training-set-48450e6f-5",
  "id_no": 7636525,
  "title": "Starter: Mitosis WSI CCMCT Training Set 48450e6f-5",
  "code_file": "starter-mitosis-wsi-ccmct-training-set-48450e6f-5.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    "datasets/marcaubreville/mitosis-wsi-ccmct-training-set"
  ],
  "kernel_sources": [],
  "competition_sources": []
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/fx6300_clam-strip-ai-train.json
{
  "id": "fx6300/clam-strip-ai-train",
  "id_no": 30722906,
  "title": "\ud83d\udc1aCLAM STRIP AI [train]\ud83d\udc1a",
  "code_file": "clam-strip-ai-train.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    ""
  ],
  "kernel_sources": [
    "code/analokamus/how-to-use-pyvips-offline"
  ],
  "competition_sources": [
    "competitions/mayo-clinic-strip-ai"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/jberros_panda-wsi-manipulation-openslide-overview.json
{
  "id": "jberros/panda-wsi-manipulation-openslide-overview",
  "id_no": 9181539,
  "title": "PANDA_WSI_Manipulation_Openslide_Overview",
  "code_file": "panda-wsi-manipulation-openslide-overview.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [
    "data visualization"
  ],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/prostate-cancer-grade-assessment"
  ]
}
