=== nali001/research_asset_search/preprocessor/notebook/schemas/kaggle_metadata_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Kaggle metadata schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the kernel"
    },
    "id_no": {
      "type": "integer",
      "description": "Numeric identifier for the kernel"
    },
    "title": {
      "type": "string",
      "description": "Title or name of the kernel"
    },
    "code_file": {
      "type": "string",
      "description": "Filename of the kernel code file"
    },
    "language": {
      "type": "string",
      "description": "Language in which the kernel is written"
    },
    "kernel_type": {
      "type": "string",
      "description": "Type of kernel"
    },
    "is_private": {
      "type": "boolean",
      "description": "Whether the kernel is private or public"
    },
    "enable_gpu": {
      "type": "boolean",
      "description": "Whether the kernel is enabled for GPU processing"
    },
    "enable_internet": {
      "type": "boolean",
      "description": "Whether the kernel has access to the internet"
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Keywords associated with the kernel"
    },
    "dataset_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any datasets used in the kernel"
    },
    "kernel_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any other kernels used in the kernel"
    },
    "competition_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any competitions used in the kernel"
    }
  },
  "required": [
    "id",
    "id_no",
    "title",
    "code_file",
    "language",
    "kernel_type",
    "is_private",
    "enable_gpu",
    "enable_internet",
    "keywords",
    "dataset_sources",
    "kernel_sources",
    "competition_sources"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/tanushrikumar_lung-cancer-wsi-efficient-net.json
{
  "id": "tanushrikumar/lung-cancer-wsi-efficient-net",
  "id_no": 24410358,
  "title": "Lung cancer WSI-Efficient net",
  "code_file": "lung-cancer-wsi-efficient-net.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    ""
  ],
  "kernel_sources": [],
  "competition_sources": []
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/micheomaano_save-mobile-wsi-patches.json
{
  "id": "micheomaano/save-mobile-wsi-patches",
  "id_no": 17463163,
  "title": "Save Mobile WSI Patches",
  "code_file": "save-mobile-wsi-patches.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [
    "datasets/micheomaano/mobilewsis"
  ],
  "kernel_sources": [],
  "competition_sources": []
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/szacho_augmix-data-augmentation-on-tpu.json
{
  "id": "szacho/augmix-data-augmentation-on-tpu",
  "id_no": 8915523,
  "title": "AugMix data augmentation on TPU",
  "code_file": "augmix-data-augmentation-on-tpu.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": true,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/flower-classification-with-tpus"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/theoviel_hubmap-final-methodology-submission.json
{
  "id": "theoviel/hubmap-final-methodology-submission",
  "id_no": 16895315,
  "title": "HubMap Final Methodology Submission",
  "code_file": "hubmap-final-methodology-submission.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [
    "neuroscience",
    "matplotlib"
  ],
  "dataset_sources": [
    ""
  ],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/hubmap-kidney-segmentation"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/sermakarevich_prepare-patches-coordinates-and-targets.json
{
  "id": "sermakarevich/prepare-patches-coordinates-and-targets",
  "id_no": 9185069,
  "title": "Prepare patches coordinates and targets",
  "code_file": "prepare-patches-coordinates-and-targets.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/prostate-cancer-grade-assessment"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/fx6300_clam-strip-ai-inference.json
{
  "id": "fx6300/clam-strip-ai-inference",
  "id_no": 30660721,
  "title": "\ud83d\udc1aCLAM STRIP AI [inference]\ud83d\udc1a",
  "code_file": "clam-strip-ai-inference.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    "datasets/fx6300/clambaseline",
    "datasets/fx6300/my-rembg",
    "datasets/fx6300/opencv-contrib",
    "datasets/fx6300/resnet50-baselinepth",
    "datasets/fx6300/tiling030",
    "datasets/fx6300/u2net-onnx"
  ],
  "kernel_sources": [
    "code/analokamus/how-to-use-pyvips-offline"
  ],
  "competition_sources": [
    "competitions/mayo-clinic-strip-ai"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/sermakarevich_micro-visuals-wsi-mask-zoom.json
{
  "id": "sermakarevich/micro-visuals-wsi-mask-zoom",
  "id_no": 9175340,
  "title": "Micro visuals: WSI * mask * zoom",
  "code_file": "micro-visuals-wsi-mask-zoom.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/prostate-cancer-grade-assessment"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/fx6300_clam-strip-ai-feature-extraction.json
{
  "id": "fx6300/clam-strip-ai-feature-extraction",
  "id_no": 30714063,
  "title": "\ud83d\udc1aCLAM STRIP AI [feature extraction]\ud83d\udc1a",
  "code_file": "clam-strip-ai-feature-extraction.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [
    "gpu"
  ],
  "dataset_sources": [
    "datasets/fx6300/4096-tiles-v4"
  ],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/mayo-clinic-strip-ai"
  ]
}
