=== nali001/research_asset_search/preprocessor/notebook/schemas/kaggle_metadata_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Kaggle metadata schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier for the kernel"
    },
    "id_no": {
      "type": "integer",
      "description": "Numeric identifier for the kernel"
    },
    "title": {
      "type": "string",
      "description": "Title or name of the kernel"
    },
    "code_file": {
      "type": "string",
      "description": "Filename of the kernel code file"
    },
    "language": {
      "type": "string",
      "description": "Language in which the kernel is written"
    },
    "kernel_type": {
      "type": "string",
      "description": "Type of kernel"
    },
    "is_private": {
      "type": "boolean",
      "description": "Whether the kernel is private or public"
    },
    "enable_gpu": {
      "type": "boolean",
      "description": "Whether the kernel is enabled for GPU processing"
    },
    "enable_internet": {
      "type": "boolean",
      "description": "Whether the kernel has access to the internet"
    },
    "keywords": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Keywords associated with the kernel"
    },
    "dataset_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any datasets used in the kernel"
    },
    "kernel_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any other kernels used in the kernel"
    },
    "competition_sources": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Sources of any competitions used in the kernel"
    }
  },
  "required": [
    "id",
    "id_no",
    "title",
    "code_file",
    "language",
    "kernel_type",
    "is_private",
    "enable_gpu",
    "enable_internet",
    "keywords",
    "dataset_sources",
    "kernel_sources",
    "competition_sources"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/prachi1211_eda-wsi-pixels.json
{
  "id": "prachi1211/eda-wsi-pixels",
  "id_no": 10316657,
  "title": "EDA - WSI Pixels ",
  "code_file": "eda-wsi-pixels.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/prostate-cancer-grade-assessment"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/dschettler8845_use-pyvips-offline-v-2-1-13.json
{
  "id": "dschettler8845/use-pyvips-offline-v-2-1-13",
  "id_no": 28815771,
  "title": "Use PyVips Offline (v. 2.1.13)",
  "code_file": "use-pyvips-offline-v-2-1-13.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": true,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    "datasets/yukkyo/pyvips-local"
  ],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/mayo-clinic-strip-ai"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/sakima_medical-whole-slide-processing-speed-up.json
{
  "id": "sakima/medical-whole-slide-processing-speed-up",
  "id_no": 29751960,
  "title": " Medical Whole Slide Processing: Speed Up!",
  "code_file": "medical-whole-slide-processing-speed-up.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/mayo-clinic-strip-ai"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/hiba007_mayo-clinic-eda-making-tiles-removing-background.json
{
  "id": "hiba007/mayo-clinic-eda-making-tiles-removing-background",
  "id_no": 29499432,
  "title": "Mayo Clinic-EDA,Making Tiles & Removing Background",
  "code_file": "mayo-clinic-eda-making-tiles-removing-background.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [
    "cv2",
    "matplotlib",
    "plotly",
    "pandas",
    "numpy"
  ],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/mayo-clinic-strip-ai"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/leahscherschel_glomeruli-detection-related-works.json
{
  "id": "leahscherschel/glomeruli-detection-related-works",
  "id_no": 12731722,
  "title": "Glomeruli Detection Related Works",
  "code_file": "glomeruli-detection-related-works.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/hubmap-kidney-segmentation"
  ]
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/haashaatif_mobile-wsi-patches-creation.json
{
  "id": "haashaatif/mobile-wsi-patches-creation",
  "id_no": 24477969,
  "title": "Mobile WSI Patches Creation",
  "code_file": "mobile-wsi-patches-creation.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    "datasets/micheomaano/mobilewsis"
  ],
  "kernel_sources": [],
  "competition_sources": []
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/tanushrikumar_wsi-monk-code.json
{
  "id": "tanushrikumar/wsi-monk-code",
  "id_no": 24359709,
  "title": "WSI - Monk code",
  "code_file": "wsi-monk-code.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": false,
  "keywords": [],
  "dataset_sources": [
    ""
  ],
  "kernel_sources": [],
  "competition_sources": []
}

=== nali001/research_asset_search/notebooksearch/Raw_notebooks/Kaggle/sermakarevich_patchslicer-generator-and-plots-of-sorted-patches.json
{
  "id": "sermakarevich/patchslicer-generator-and-plots-of-sorted-patches",
  "id_no": 9119256,
  "title": "PatchSlicer generator and plots of sorted patches ",
  "code_file": "patchslicer-generator-and-plots-of-sorted-patches.ipynb",
  "language": "python",
  "kernel_type": "notebook",
  "is_private": false,
  "enable_gpu": false,
  "enable_internet": true,
  "keywords": [
    "data visualization"
  ],
  "dataset_sources": [],
  "kernel_sources": [],
  "competition_sources": [
    "competitions/prostate-cancer-grade-assessment"
  ]
}
